import './globals.scss'
import { Inter } from 'next/font/google'
import { Providers } from './provider'
import HeaderServer from '@/components/Header/HeaderServer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dreadew',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <HeaderServer />
          {children}
        </body>
      </Providers>
    </html>
  )
}
