import './globals.scss'
import { Inter } from 'next/font/google'
import { Providers } from './provider'
import Header from '@/components/Header/Header'
import { checkAuth } from '@/utils/checkAuth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dreadew',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const isAuthorized = await checkAuth();
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Header isAuthorized={isAuthorized} />
          {children}
        </body>
      </Providers>
    </html>
  )
}
